### ISSUE TITLE
Feature Request: Add support for Plank Make as an activity

### ISSUE THREAD

**Issue by Mhkeane** [Car-Role/Distraction-Reducer#3]
Hi,

I was wondering if you might be able to add support for use of the Plank Make spell as one of the skilling toggles? While Plank Make can be manually cast to speed it up, it's also possible to leave it to run automatically, which is a slightly profitable and low intensity magic training method. I've been really enjoying this plugin, and was hoping you might expand it to support this too. 

Other, similar spells that might be good additions if you were making changes in this space are Enchant Jewelry and Charge Orb from the standard spellbook, as well as Bake Pie and String Jewelry from the Lunar spellbook.

Thank you very much for the plugin!

**Comment by TV-cmd** [comment]
Good idea @Car-Role 'sup

**Comment by Car-Role** [comment]
commit e1582cf3d151774d175b2973e9e9823d9725ca5e solved
