### ISSUE TITLE
Firemaking

### ISSUE THREAD

**Issue by Fincher07** [Car-Role/Distraction-Reducer#6]
I like using the plugin, but is there any chance you can make it work for firemaking too? I'd like to use it at wintertodt when feeding the brazier and also bonfires maybe. =)

**Comment by Car-Role** [comment]
Added bonfires and firemaking support a6da764421d8f9c72a42814a59e994da07a3c502

I opted out of supporting braziers as it opens the door for minigame support which I don't plan to at this moment
