### ISSUE TITLE
Cutting uncut gems not functioning

### ISSUE THREAD

**Issue by Pimmalage** [Car-Role/Distraction-Reducer#7]
When cutting uncut gems only sapphires seemingly work.
Tried Ruby, Diamond and emerald - not functioning
If for some reason it's a specific setting causing it i have both Herblore and Mining disabled. Restore delay set to 3.

**Comment by Car-Role** [comment]
Fixed in 9271106dd3a9c90fe6cb952b0d41efe3b42cb7d0
